import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja" // enからjaにしておきましょう！
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* classNameの "flex flex-col" を消して、全画面表示を優先させます */}
      <body className="min-h-full">
        {children}
      </body>
    </html>
  );
}
